logging:
  debug:
    enable: true
    level: 1

########## Chat Settings ##########
# You can use the complete AdventureAPI Syntax here
chat:
  # The Chat format shown in the chat
  # Placeholders: <prefix>, <name>, <message>, <group>
  # Default Minecraft message format: '<white><<name>>: <message>'
  format: '<prefix> <dark_gray>| <gray><hover:show_text:"<gray>Group: <blue><group><br><gray>Prefix:<prefix>"><name><reset> <dark_gray>» <gray><message>'

  join-message:
    # If set to false, the default join message will be used
    enable: true
    # The format of the join message
    # Placeholders: <prefix>, <name>
    message: <gray>『<green><bold>▲<reset><gray>』 <reset><prefix><reset> <dark_gray>| <gray><name><reset> <dark_gray>» <green>joined the server.

  quit-message:
    # If set to false, the default quit message will be used
    enable: true
    # The format of the quit message
    # Placeholders: <prefix>, <name>
    message: <gray>『<red><bold>▼<reset><gray>』 <reset><prefix><reset> <dark_gray>| <gray><name><reset> <dark_gray>» <red>left the server.

########## Tablist Settings ##########
# You can use the complete AdventureAPI Syntax here
tablist:
  # The playername format shown in the tablist
  # Placeholders: <prefix>, <name>
  name-format: <prefix> <white><name>
  sort-players-by-ranks: true

storage:
  # possible values:
  # - sqlite -> using SQLite (recommended for most users) (single server setup)
  # - mysql -> for a MySQL database
  # - mariadb -> for a MariaDB database (recommended over MySQL)
  type: sqlite
  host: 127.0.0.1
  port: 3306
  database: databaseName
  username: username
  password: YourSecretPassword
  advanced:
    use-ssl: false
    connection-timeout: 60000
    idle-timeout: 600000
    keep-alive-time: 0
    max-life-time: 1800000
    minimum-idle: 10
    maximum-pool-size: 10
    leak-detection-threshold: 0
    connection-test-query: "SELECT 1"
    character-encoding: "utf8"